[package]
name = "barcode"
version = "0.1.0"
edition = "2024"

[dependencies]
crossterm = "0.29.0"
clap = { version = "4.5.50", features = ["derive"] }
chrono = { version = "0.4", features = ["serde", "clock"] }
colored = "3.0.0"
